apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: redis-app
  name: redis-app
spec:
  containers:
  - image: redis
    name: redis-app
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
